#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Wac2015.Droid.Resource", IsApplication=true)]

namespace Wac2015.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ByteSmith.WindowsAzure.Messaging.Resource.String.library_name = global::Wac2015.Droid.Resource.String.library_name;
			global::Gcm.Client.Resource.String.library_name = global::Wac2015.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Wac2015.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Wac2015.Droid.Resource.String.Hello;
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::Wac2015.Droid.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::Wac2015.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int blur = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int blur_radius = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int ratio = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int splash_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ApplicationIconW = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int azurelogo_100 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int azurelogo_30 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int evolve_logo_blue = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int evolve_logo_white = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int evolve_splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hamburgerIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int heart2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int heart2empty = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_social_share = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_background_evolve = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_launcher = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_navigate = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_pin_blue = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_pin_purple = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_stat_hexagon_blue = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int missing = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int missing_banner = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int missing_banner_blurred = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int missingprofile = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int presentation = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int refresh = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int slideout = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int splash = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int splash3 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int splashscreen = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int twitter = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int app_name = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			// aapt resource value: 0x7f030004
			public const int share = 2130903044;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BlurredImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int BlurredImageView_blur = 1;
			
			// aapt resource value: 2
			public const int BlurredImageView_blur_radius = 2;
			
			// aapt resource value: 0
			public const int BlurredImageView_ratio = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
